root: true
env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:import/errors',
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - 'google'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslist'
parser: "@typescript-eslint/parser"
parserOptions:
  project: ["tsconfig.json", "tsconfig.dev.json"]
  sourceType: "module"
ignorePatterns:
  - "/lib/**/*", // Ignore built files.
plugins:
  - "@typescript-eslint"
  - "import"
rules:
  quotes: ["error", "double"]
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/consistent-type-assertions':
    [warn, { assertionStyle: 'as' }]
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-floating-promises': 'error'
  '@typescript-eslint/no-parameter-properties': off
  'custom-rules/disallow-src-dist-import': error
  'custom-rules/disable-barreling': error
  'no-console': warn

